version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - goodevilgenius
  labels:
  - dependencies
  ignore:
  - dependency-name: sprockets
    versions:
    - ">= 4.a, < 5"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
