baseURL = "https://danielrayjones.com/"
languageCode = "en-us"
title = "Dan Jones"
theme = "hello-friend-ng"
enableGitInfo = true

[params]
homeSubtitle = "Web developer, actor, jack of some trades"
EnableThemeToggle = true

[params.logo]
logoText = "RUN"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[menu.main]]
identifier = "web"
name = "Web Résumé"
url = "/web"
weight = 10

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 50
