baseURL = "https://danielrayjones.com/"
languageCode = "en-us"
title = "Dan Jones"
theme = "hello-friend-ng"

[params]
homeSubtitle = "Web developer, actor, jack of some trades"
EnableThemeToggle = true

[params.logo]
logoText = "RUN"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
