version: 2
jobs:
  build:
    branches:
      only: [master]
    working_directory: /tmp/danielrayjones
    docker:
      - image: hugomods/hugo:0.120.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "23:c0:43:4c:ae:5b:92:a6:5b:79:92:6b:ca:62:59:8d"
      - checkout
      - run:
          name: Configure git user
          command: |
            git config --global user.email "ci@danielrayjones.com"
            git config --global user.name "Circle CI"
      - run:
          name: Install dependencies
          command: |
            apk add openssh
            ssh-keyscan -H codeberg.org > ~/.ssh/known_hosts
            git submodule init
            git submodule update
      - run:
          name: Creating build directory
          command: git clone -b gh-pages `git remote get-url origin` public
      - run:
          name: Build site
          command: hugo --cleanDestinationDir
      - run:
          name: No Jekyll
          command: touch public/.nojekyll
      - run:
          name: Deploy site
          command: |
            cd public
            git add -A
            git commit -m "$(date --iso-8601=seconds) Deploy new site"
            git push
